//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.06 at 05:48:20 PM GST 
//


package com.emirates.dash.location.vo;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="region" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="country" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="city" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="airport" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="DefaultAirport" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                               &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                               &lt;attribute name="icaocode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="tz" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="AMAirport" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="NoOLPP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="BusStation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="NoOLCI" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="location" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                     &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                     &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="tz" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="labelplacement" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="zoomLevel" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="otherRegions" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="NoOLCI" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "region"
})
@XmlRootElement(name = "list")
public class List {

    protected java.util.List<List.Region> region;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the region property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the region property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link List.Region }
     * 
     * 
     */
    public java.util.List<List.Region> getRegion() {
        if (region == null) {
            region = new ArrayList<List.Region>();
        }
        return this.region;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="country" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="city" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="airport" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="DefaultAirport" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                                     &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                                     &lt;attribute name="icaocode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="tz" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="AMAirport" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="NoOLPP" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="BusStation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="NoOLCI" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="location" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                           &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                           &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="tz" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="labelplacement" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="zoomLevel" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="otherRegions" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="NoOLCI" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "country"
    })
    public static class Region {

        protected java.util.List<List.Region.Country> country;
        @XmlAttribute(name = "id")
        protected Integer id;
        @XmlAttribute(name = "code")
        protected String code;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "shortname")
        protected String shortname;

        /**
         * Gets the value of the country property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the country property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCountry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link List.Region.Country }
         * 
         * 
         */
        public java.util.List<List.Region.Country> getCountry() {
            if (country == null) {
                country = new ArrayList<List.Region.Country>();
            }
            return this.country;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setId(Integer value) {
            this.id = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the shortname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortname() {
            return shortname;
        }

        /**
         * Sets the value of the shortname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShortname(String value) {
            this.shortname = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="city" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="airport" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="DefaultAirport" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                           &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                           &lt;attribute name="icaocode" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="tz" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="AMAirport" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="NoOLPP" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="BusStation" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="NoOLCI" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="location" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                 &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                 &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="tz" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="labelplacement" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="zoomLevel" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="otherRegions" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="NoOLCI" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "city"
        })
        public static class Country {

            protected java.util.List<List.Region.Country.City> city;
            @XmlAttribute(name = "id")
            protected Integer id;
            @XmlAttribute(name = "code")
            protected String code;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "shortname")
            protected String shortname;
            @XmlAttribute(name = "latitude")
            protected Float latitude;
            @XmlAttribute(name = "longitude")
            protected Float longitude;
            @XmlAttribute(name = "otherRegions")
            protected Integer otherRegions;
            @XmlAttribute(name = "NoOLCI")
            protected String noOLCI;

            /**
             * Gets the value of the city property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the city property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCity().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link List.Region.Country.City }
             * 
             * 
             */
            public java.util.List<List.Region.Country.City> getCity() {
                if (city == null) {
                    city = new ArrayList<List.Region.Country.City>();
                }
                return this.city;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setId(Integer value) {
                this.id = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the shortname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShortname() {
                return shortname;
            }

            /**
             * Sets the value of the shortname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShortname(String value) {
                this.shortname = value;
            }

            /**
             * Gets the value of the latitude property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setLatitude(Float value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setLongitude(Float value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the otherRegions property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getOtherRegions() {
                return otherRegions;
            }

            /**
             * Sets the value of the otherRegions property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setOtherRegions(Integer value) {
                this.otherRegions = value;
            }

            /**
             * Gets the value of the noOLCI property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoOLCI() {
                return noOLCI;
            }

            /**
             * Sets the value of the noOLCI property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoOLCI(String value) {
                this.noOLCI = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="airport" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="DefaultAirport" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
             *                 &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
             *                 &lt;attribute name="icaocode" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="tz" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="AMAirport" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="NoOLPP" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="BusStation" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="NoOLCI" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="location" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
             *       &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
             *       &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="tz" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="labelplacement" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="zoomLevel" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "airport",
                "location"
            })
            public static class City {

                protected java.util.List<List.Region.Country.City.Airport> airport;
                protected java.util.List<List.Region.Country.City.Location> location;
                @XmlAttribute(name = "id")
                protected Integer id;
                @XmlAttribute(name = "code")
                protected String code;
                @XmlAttribute(name = "name")
                protected String name;
                @XmlAttribute(name = "shortname")
                protected String shortname;
                @XmlAttribute(name = "latitude")
                protected Float latitude;
                @XmlAttribute(name = "longitude")
                protected Float longitude;
                @XmlAttribute(name = "timezone")
                protected String timezone;
                @XmlAttribute(name = "tz")
                protected String tz;
                @XmlAttribute(name = "labelplacement")
                protected String labelplacement;
                @XmlAttribute(name = "zoomLevel")
                protected Byte zoomLevel;

                /**
                 * Gets the value of the airport property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the airport property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAirport().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link List.Region.Country.City.Airport }
                 * 
                 * 
                 */
                public java.util.List<List.Region.Country.City.Airport> getAirport() {
                    if (airport == null) {
                        airport = new ArrayList<List.Region.Country.City.Airport>();
                    }
                    return this.airport;
                }

                /**
                 * Gets the value of the location property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the location property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getLocation().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link List.Region.Country.City.Location }
                 * 
                 * 
                 */
                public java.util.List<List.Region.Country.City.Location> getLocation() {
                    if (location == null) {
                        location = new ArrayList<List.Region.Country.City.Location>();
                    }
                    return this.location;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setId(Integer value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCode(String value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the shortname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShortname() {
                    return shortname;
                }

                /**
                 * Sets the value of the shortname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShortname(String value) {
                    this.shortname = value;
                }

                /**
                 * Gets the value of the latitude property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Float }
                 *     
                 */
                public Float getLatitude() {
                    return latitude;
                }

                /**
                 * Sets the value of the latitude property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Float }
                 *     
                 */
                public void setLatitude(Float value) {
                    this.latitude = value;
                }

                /**
                 * Gets the value of the longitude property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Float }
                 *     
                 */
                public Float getLongitude() {
                    return longitude;
                }

                /**
                 * Sets the value of the longitude property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Float }
                 *     
                 */
                public void setLongitude(Float value) {
                    this.longitude = value;
                }

                /**
                 * Gets the value of the timezone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTimezone() {
                    return timezone;
                }

                /**
                 * Sets the value of the timezone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTimezone(String value) {
                    this.timezone = value;
                }

                /**
                 * Gets the value of the tz property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTz() {
                    return tz;
                }

                /**
                 * Sets the value of the tz property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTz(String value) {
                    this.tz = value;
                }

                /**
                 * Gets the value of the labelplacement property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLabelplacement() {
                    return labelplacement;
                }

                /**
                 * Sets the value of the labelplacement property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLabelplacement(String value) {
                    this.labelplacement = value;
                }

                /**
                 * Gets the value of the zoomLevel property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getZoomLevel() {
                    return zoomLevel;
                }

                /**
                 * Sets the value of the zoomLevel property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setZoomLevel(Byte value) {
                    this.zoomLevel = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="DefaultAirport" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
                 *       &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
                 *       &lt;attribute name="icaocode" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="tz" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="AMAirport" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="NoOLPP" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="BusStation" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="NoOLCI" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Airport {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "id")
                    protected Integer id;
                    @XmlAttribute(name = "code")
                    protected String code;
                    @XmlAttribute(name = "name")
                    protected String name;
                    @XmlAttribute(name = "shortname")
                    protected String shortname;
                    @XmlAttribute(name = "DefaultAirport")
                    protected String defaultAirport;
                    @XmlAttribute(name = "latitude")
                    protected Float latitude;
                    @XmlAttribute(name = "longitude")
                    protected Float longitude;
                    @XmlAttribute(name = "icaocode")
                    protected String icaocode;
                    @XmlAttribute(name = "timezone")
                    protected String timezone;
                    @XmlAttribute(name = "tz")
                    protected String tz;
                    @XmlAttribute(name = "AMAirport")
                    protected String amAirport;
                    @XmlAttribute(name = "NoOLPP")
                    protected String noOLPP;
                    @XmlAttribute(name = "BusStation")
                    protected String busStation;
                    @XmlAttribute(name = "NoOLCI")
                    protected String noOLCI;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setId(Integer value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the code property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCode() {
                        return code;
                    }

                    /**
                     * Sets the value of the code property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCode(String value) {
                        this.code = value;
                    }

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the shortname property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getShortname() {
                        return shortname;
                    }

                    /**
                     * Sets the value of the shortname property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setShortname(String value) {
                        this.shortname = value;
                    }

                    /**
                     * Gets the value of the defaultAirport property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDefaultAirport() {
                        return defaultAirport;
                    }

                    /**
                     * Sets the value of the defaultAirport property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDefaultAirport(String value) {
                        this.defaultAirport = value;
                    }

                    /**
                     * Gets the value of the latitude property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Float }
                     *     
                     */
                    public Float getLatitude() {
                        return latitude;
                    }

                    /**
                     * Sets the value of the latitude property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Float }
                     *     
                     */
                    public void setLatitude(Float value) {
                        this.latitude = value;
                    }

                    /**
                     * Gets the value of the longitude property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Float }
                     *     
                     */
                    public Float getLongitude() {
                        return longitude;
                    }

                    /**
                     * Sets the value of the longitude property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Float }
                     *     
                     */
                    public void setLongitude(Float value) {
                        this.longitude = value;
                    }

                    /**
                     * Gets the value of the icaocode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIcaocode() {
                        return icaocode;
                    }

                    /**
                     * Sets the value of the icaocode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIcaocode(String value) {
                        this.icaocode = value;
                    }

                    /**
                     * Gets the value of the timezone property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTimezone() {
                        return timezone;
                    }

                    /**
                     * Sets the value of the timezone property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTimezone(String value) {
                        this.timezone = value;
                    }

                    /**
                     * Gets the value of the tz property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTz() {
                        return tz;
                    }

                    /**
                     * Sets the value of the tz property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTz(String value) {
                        this.tz = value;
                    }

                    /**
                     * Gets the value of the amAirport property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAMAirport() {
                        return amAirport;
                    }

                    /**
                     * Sets the value of the amAirport property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAMAirport(String value) {
                        this.amAirport = value;
                    }

                    /**
                     * Gets the value of the noOLPP property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNoOLPP() {
                        return noOLPP;
                    }

                    /**
                     * Sets the value of the noOLPP property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNoOLPP(String value) {
                        this.noOLPP = value;
                    }

                    /**
                     * Gets the value of the busStation property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBusStation() {
                        return busStation;
                    }

                    /**
                     * Sets the value of the busStation property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBusStation(String value) {
                        this.busStation = value;
                    }

                    /**
                     * Gets the value of the noOLCI property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNoOLCI() {
                        return noOLCI;
                    }

                    /**
                     * Sets the value of the noOLCI property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNoOLCI(String value) {
                        this.noOLCI = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Location {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "id")
                    protected Integer id;
                    @XmlAttribute(name = "code")
                    protected String code;
                    @XmlAttribute(name = "name")
                    protected String name;
                    @XmlAttribute(name = "shortname")
                    protected String shortname;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setId(Integer value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the code property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCode() {
                        return code;
                    }

                    /**
                     * Sets the value of the code property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCode(String value) {
                        this.code = value;
                    }

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the shortname property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getShortname() {
                        return shortname;
                    }

                    /**
                     * Sets the value of the shortname property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setShortname(String value) {
                        this.shortname = value;
                    }

                }

            }

        }

    }

}
